sudo rm -rf /home/mo/.cache/racket
sudo rm -rf /home/mo/source/racket-8.6.0.2
sudo rm -rf /home/mo/.local/share/racket
sudo rm -rf /usr/local/include/racket
sudo rm -rf /usr/local/bin/racket
sudo rm -rf /usr/local/etc/racket
sudo rm -rf /usr/local/lib/racket
sudo rm -rf /usr/local/share/man/man1/racket*
sudo rm -rf /usr/local/share/doc/racket
sudo rm -rf /usr/local/share/racket
find /usr -name 'racket*'
find /home -name 'racket*'
